In [1]:
import cv2
import math
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib inline
from keras.preprocessing import image
import numpy as np
#from google.colab.patches import cv2_imshow
import os
import sys
from PIL import Image

Using TensorFlow backend.


In [2]:
# load json and create model
#load the model 
from keras.models import model_from_json
json_file = open('EmotionBinary2.json', 'r')
loaded_model_json = json_file.read()
json_file.close()
loaded_model = model_from_json(loaded_model_json)
# load weights into new model
loaded_model.load_weights("EmotionBinary2.h5")
print("Loaded model from disk")

Loaded model from disk


In [3]:
# Compiling and Making New Predictions

# compile loaded model on test data
loaded_model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])


#checking camara

import cv2

# Capture video from file
#cap = cv2.VideoCapture("C:\\Users\\Allworx User 2.ALLWORXW2\\Videos\\Wildlife.wmv")
cap = cv2.VideoCapture(0)
#cap.set(5, 10)
frameRate = cap.get(5)
print(frameRate)


while True:
   
    ret, frame = cap.read()
   
    print(fps)

    if ret == True:

        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

        cv2.imshow('frame',gray)
       


        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

    else:
        break

cap.release()
cv2.destroyAllWindows()



In [4]:
import numpy as np
from keras.preprocessing import image
font = cv2.FONT_HERSHEY_SIMPLEX
#face_cascade = cv2.CascadeClassifier("C:\\Users\\kamma\\Anaconda3\\envs\\vdpnLeP35\\Library\\etc\\haarcascades\\haarcascade_frontalface_default.xml")
#face_cascade = cv2.CascadeClassifier("C:\\Users\\kamma\\Anaconda3\\envs\\vdpnLeP35\\Library\\etc\\haarcascades\\haarcascade_frontalface_alt_tree.xml")
face_cascade = cv2.CascadeClassifier("C:\\Users\Allworx User 2.ALLWORXW2\\Anaconda3\\envs\\tf15\\Library\\etc\\haarcascades\\haarcascade_frontalface_default.xml")
#face_cascade = cv2.CascadeClassifier("C:\\Users\\kamma\\Anaconda3\\envs\\vdpnLeP35\\Library\\etc\\haarcascades\\haarcascade_frontalface_alt2.xml")

cap = cv2.VideoCapture(0)
cap.set(5, 30)
frameRate = cap.get(5)
print(frameRate)
count=0
while True:
    #current frame number--this is for frame rate
    count+=1
    frameId=count
    ret, img = cap.read()
    #frameId = cap.get(1)
    #show the mark on face
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(gray, 1.3, 5)
    print(frameId)
    print(frameRate)
    if (frameId % (math.floor((frameRate/5))) == 0):
        print("Inside if ")
        for (x,y,w,h) in faces:
            print(faces)
            print("inside for loop")
            print(x,y,w,h)
            cv2.rectangle(img, (x,y), (x+w, y+h), (0,255,0), 5)  #2 is width of the line 
            #roi_gray = gray[y:y+h, x:x+w]
            #roi_color = img[y:y+h, x:x+w]
            #pridicting with model 
            #converting ndarray to image
            filename ="vijay.jpg"
            crop_img = img[y:y+h, x:x+w]
            cv2.imwrite(filename, crop_img) 
            
            test_image = image.load_img("vijay.jpg", target_size = (64, 64))
            test_image = image.img_to_array(test_image)
            test_image = np.expand_dims(test_image, axis = 0)
            result = loaded_model.predict(test_image)          
            #result = loaded_model.predict(img[y:y+h, x:x+w])
            #training_set.class_indices
            if result[0][0] == 1:
                prediction = 'Smile'
            elif result[0][0] == 0 :
                prediction = 'Anger'
            else:
                prediction = 'Nutral'    
            print(prediction)
            #Write text on the rectanguler box.
            cv2.putText(img, prediction, (286, 104), font, 0.8, (0, 0, 255), 3, cv2.LINE_AA)     
            cv2.imshow('img',img)
            cv2.imshow('crop_img',crop_img)
    k= cv2.waitKey(5) & 0xff
    if k==27:
        break
        
cv2.destroyAllWindows()
cap.release()

30.00003000003
1
30.00003000003
2
30.00003000003
3
30.00003000003
4
30.00003000003
5
30.00003000003
6
30.00003000003
Inside if 
7
30.00003000003
8
30.00003000003
9
30.00003000003
10
30.00003000003
11
30.00003000003
12
30.00003000003
Inside if 
13
30.00003000003
14
30.00003000003
15
30.00003000003
16
30.00003000003
17
30.00003000003
18
30.00003000003
Inside if 
[[ 30  60 226 226]]
inside for loop
30 60 226 226
Smile
19
30.00003000003
20
30.00003000003
21
30.00003000003
22
30.00003000003
23
30.00003000003
24
30.00003000003
Inside if 
[[ 26  58 233 233]]
inside for loop
26 58 233 233
Smile
25
30.00003000003
26
30.00003000003
27
30.00003000003
28
30.00003000003
29
30.00003000003
30
30.00003000003
Inside if 
[[ 25  59 229 229]]
inside for loop
25 59 229 229
Smile
31
30.00003000003
32
30.00003000003
33
30.00003000003
34
30.00003000003
35
30.00003000003
36
30.00003000003
Inside if 
[[ 32  61 218 218]]
inside for loop
32 61 218 218
Smile
37
30.00003000003
38
30.00003000003
39
30.00003000003
40

340
30.00003000003
341
30.00003000003
342
30.00003000003
Inside if 
343
30.00003000003
344
30.00003000003
345
30.00003000003
346
30.00003000003
347
30.00003000003
348
30.00003000003
Inside if 
349
30.00003000003
350
30.00003000003
351
30.00003000003
352
30.00003000003
353
30.00003000003
354
30.00003000003
Inside if 
[[ 33  65 211 211]]
inside for loop
33 65 211 211
Smile
355
30.00003000003
356
30.00003000003
357
30.00003000003
358
30.00003000003
359
30.00003000003
360
30.00003000003
Inside if 
361
30.00003000003
362
30.00003000003
363
30.00003000003
364
30.00003000003
365
30.00003000003
366
30.00003000003
Inside if 
367
30.00003000003
368
30.00003000003
369
30.00003000003
370
30.00003000003
371
30.00003000003
372
30.00003000003
Inside if 
373
30.00003000003
374
30.00003000003
375
30.00003000003
376
30.00003000003
377
30.00003000003
378
30.00003000003
Inside if 
379
30.00003000003
380
30.00003000003
381
30.00003000003
382
30.00003000003
383
30.00003000003
384
30.00003000003
Inside if 
3

726
30.00003000003
Inside if 
[[292  57 255 255]]
inside for loop
292 57 255 255
Anger
727
30.00003000003
728
30.00003000003
729
30.00003000003
730
30.00003000003
731
30.00003000003
732
30.00003000003
Inside if 
[[316  58 255 255]]
inside for loop
316 58 255 255
Anger
733
30.00003000003
734
30.00003000003
735
30.00003000003
736
30.00003000003
737
30.00003000003
738
30.00003000003
Inside if 
[[300  67 248 248]]
inside for loop
300 67 248 248
Anger
739
30.00003000003
740
30.00003000003
741
30.00003000003
742
30.00003000003
743
30.00003000003
744
30.00003000003
Inside if 
[[275  78 230 230]]
inside for loop
275 78 230 230
Anger
745
30.00003000003
746
30.00003000003
747
30.00003000003
748
30.00003000003
749
30.00003000003
750
30.00003000003
Inside if 
751
30.00003000003
752
30.00003000003
753
30.00003000003
754
30.00003000003
755
30.00003000003
756
30.00003000003
Inside if 
[[224  95 216 216]]
inside for loop
224 95 216 216
Nutral
757
30.00003000003
758
30.00003000003
759
30.00003000003
76

1021
30.00003000003
1022
30.00003000003
1023
30.00003000003
1024
30.00003000003
1025
30.00003000003
1026
30.00003000003
Inside if 
1027
30.00003000003
1028
30.00003000003
1029
30.00003000003
1030
30.00003000003
1031
30.00003000003
1032
30.00003000003
Inside if 
1033
30.00003000003
1034
30.00003000003
1035
30.00003000003
1036
30.00003000003
1037
30.00003000003
1038
30.00003000003
Inside if 
1039
30.00003000003
1040
30.00003000003
1041
30.00003000003
1042
30.00003000003
1043
30.00003000003
1044
30.00003000003
Inside if 
1045
30.00003000003
1046
30.00003000003
1047
30.00003000003
1048
30.00003000003
1049
30.00003000003
1050
30.00003000003
Inside if 
1051
30.00003000003
1052
30.00003000003
1053
30.00003000003
1054
30.00003000003
1055
30.00003000003
1056
30.00003000003
Inside if 
[[383  77 237 237]]
inside for loop
383 77 237 237
Anger
1057
30.00003000003
1058
30.00003000003
1059
30.00003000003
1060
30.00003000003
1061
30.00003000003
1062
30.00003000003
Inside if 
[[334  90 235 235]]
inside

30.00003000003
1332
30.00003000003
Inside if 
1333
30.00003000003
1334
30.00003000003
1335
30.00003000003
1336
30.00003000003
1337
30.00003000003
1338
30.00003000003
Inside if 
1339
30.00003000003
1340
30.00003000003
1341
30.00003000003
1342
30.00003000003
1343
30.00003000003
1344
30.00003000003
Inside if 
1345
30.00003000003
1346
30.00003000003
1347
30.00003000003
1348
30.00003000003
1349
30.00003000003
1350
30.00003000003
Inside if 
1351
30.00003000003
1352
30.00003000003
1353
30.00003000003
1354
30.00003000003
1355
30.00003000003
1356
30.00003000003
Inside if 
1357
30.00003000003
1358
30.00003000003
1359
30.00003000003
1360
30.00003000003
1361
30.00003000003
1362
30.00003000003
Inside if 
1363
30.00003000003
1364
30.00003000003
1365
30.00003000003
1366
30.00003000003
1367
30.00003000003
1368
30.00003000003
Inside if 
1369
30.00003000003
1370
30.00003000003
1371
30.00003000003
1372
30.00003000003
1373
30.00003000003
1374
30.00003000003
Inside if 
1375
30.00003000003
1376
30.000030000

1686
30.00003000003
Inside if 
1687
30.00003000003
1688
30.00003000003
1689
30.00003000003
